targets:
  $default:
    builders:
      json_serializable:
        options:
          explicit_to_json: true
      freezed:
        options:
          # Tells Freezed not to format .freezed.dart files.
          # This can significantly speed up code-generation.
          format: false
          map: false
          when: false
