name: travel_exchanger
description: A new Flutter project.
publish_to: none
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  firebase_core: 2.29.0

  intl: any
  flutter_hooks: ^0.20.5
  hooks_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  freezed_annotation: ^2.4.1
  dart_mappable: ^4.2.1
  json_annotation: ^4.8.1
  provider: ^6.1.2
  logger: ^2.1.0
  equatable: ^2.0.5
  flutter_svg: ^2.0.8
  fpdart: ^1.1.0
  shared_preferences: ^2.2.2
  collection: ^1.17.2
  url_launcher: ^6.2.1
  flutter_dotenv: ^5.1.0
  go_router: ^13.2.0
  supabase_flutter: ^2.3.4
  slang: ^3.29.0
  slang_flutter: ^3.29.0
  flutter_portal: ^1.1.4
  flutter_animate: ^4.5.0
  flutter_lucide: ^1.1.2
  google_fonts: ^6.1.0
  auto_size_text: ^3.0.0
  theme_tailor_annotation: ^3.0.1
  fluttertoast: ^8.2.4
  gap: ^3.0.1

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  custom_lint: ^0.6.0
  riverpod_lint: ^2.3.3

  # TODO: Remove later
  dart_code_metrics_presets: ^2.9.0

  build_runner: ^2.4.6
  riverpod_generator: ^2.4.0
  freezed: ^2.4.5
  dart_mappable_builder: ^4.2.1
  json_serializable: ^6.7.1
  go_router_builder: ^2.4.1
  theme_tailor: ^3.0.1

  melos: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - .env

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
